[package]
name = "awsutil"
version = "0.1.0"
authors = ["xKerman <xKhorasan@gmail.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.1"
rusoto_core = "0.36.0"
rusoto_sns = "0.36.0"
rusoto_ssm = "0.36.0"
